from __future__ import annotations

FileSignal = tuple[str, str, str]


FILE_SIGNALS: list[FileSignal] = [
    # CI/CD
    (".github/workflows/*.yml", "GitHub Actions", "cicd"),
    (".github/workflows/*.yaml", "GitHub Actions", "cicd"),
    (".gitlab-ci.yml", "GitLab CI", "cicd"),
    (".circleci/config.yml", "CircleCI", "cicd"),
    ("Jenkinsfile", "Jenkins", "cicd"),
    ("azure-pipelines.yml", "Azure Pipelines", "cicd"),
    ("bitbucket-pipelines.yml", "Bitbucket Pipelines", "cicd"),
    (".buildkite/pipeline.yml", "Buildkite", "cicd"),
    (".drone.yml", "Drone", "cicd"),
    # Infra / runtime
    ("Dockerfile", "Docker", "infra"),
    ("Dockerfile.*", "Docker", "infra"),
    (".dockerignore", "Docker", "infra"),
    ("compose.yaml", "Docker Compose", "infra"),
    ("compose.yml", "Docker Compose", "infra"),
    ("docker-compose.yaml", "Docker Compose", "infra"),
    ("docker-compose.yml", "Docker Compose", "infra"),
    (".devcontainer/devcontainer.json", "Dev Containers", "infra"),
    ("deployment.yaml", "Kubernetes", "infra"),
    ("service.yaml", "Kubernetes", "infra"),
    ("ingress.yaml", "Kubernetes", "infra"),
    ("configmap.yaml", "Kubernetes", "infra"),
    ("secret.yaml", "Kubernetes", "infra"),
    ("k8s/*.yaml", "Kubernetes", "infra"),
    ("manifests/*.yaml", "Kubernetes", "infra"),
    ("Chart.yaml", "Helm", "infra"),
    ("values.yaml", "Helm", "infra"),
    ("templates/*.yaml", "Helm", "infra"),
    ("kustomization.yaml", "Kustomize", "infra"),
    ("*.tf", "Terraform", "infra"),
    ("*.tfvars", "Terraform", "infra"),
    ("providers.tf", "Terraform", "infra"),
    ("backend.tf", "Terraform", "infra"),
    ("versions.tf", "Terraform", "infra"),
    ("terragrunt.hcl", "Terragrunt", "infra"),
    ("Pulumi.yaml", "Pulumi", "infra"),
    ("Pulumi.*.yaml", "Pulumi", "infra"),
    ("serverless.yml", "Serverless", "infra"),
    ("sst.config.ts", "Serverless", "infra"),
    ("template.yaml", "Serverless", "infra"),
    ("fly.toml", "Cloud Deploy", "infra"),
    ("railway.toml", "Cloud Deploy", "infra"),
    ("render.yaml", "Cloud Deploy", "infra"),
    ("vercel.json", "Cloud Deploy", "infra"),
    ("netlify.toml", "Cloud Deploy", "infra"),
    ("app.yaml", "Cloud Deploy", "infra"),
    ("Procfile", "Cloud Deploy", "infra"),
    # Monorepo / build systems
    ("pnpm-workspace.yaml", "pnpm Workspace", "monorepo"),
    ("turbo.json", "Turborepo", "monorepo"),
    ("nx.json", "Nx", "monorepo"),
    ("workspace.json", "Nx", "monorepo"),
    ("project.json", "Nx", "monorepo"),
    ("lerna.json", "Lerna", "monorepo"),
    ("WORKSPACE", "Bazel", "monorepo"),
    ("MODULE.bazel", "Bazel", "monorepo"),
    ("BUILD", "Bazel", "monorepo"),
    ("BUILD.bazel", "Bazel", "monorepo"),
    ("pants.toml", "Pants", "monorepo"),
    (".buckconfig", "Buck", "monorepo"),
    ("BUCK", "Buck", "monorepo"),
    ("Makefile", "Make", "monorepo"),
    ("Taskfile.yml", "Task", "monorepo"),
    ("Taskfile.yaml", "Task", "monorepo"),
    ("justfile", "Just", "monorepo"),
    # Frameworks
    ("next.config.js", "Next.js", "framework"),
    ("next.config.mjs", "Next.js", "framework"),
    ("next.config.ts", "Next.js", "framework"),
    ("vite.config.ts", "Vite", "framework"),
    ("vite.config.js", "Vite", "framework"),
    ("nuxt.config.ts", "Nuxt", "framework"),
    ("nuxt.config.js", "Nuxt", "framework"),
    ("astro.config.*", "Astro", "framework"),
    ("svelte.config.js", "SvelteKit", "framework"),
    ("svelte.config.ts", "SvelteKit", "framework"),
    ("angular.json", "Angular", "framework"),
    ("app.json", "Expo", "framework"),
    ("app.config.ts", "Expo", "framework"),
    ("eas.json", "Expo", "framework"),
    ("AndroidManifest.xml", "Android", "framework"),
    ("libs.versions.toml", "Android", "framework"),
    ("manage.py", "Django", "framework"),
    ("settings.py", "Django", "framework"),
    ("asgi.py", "Django", "framework"),
    ("wsgi.py", "Django", "framework"),
    ("config/routes.rb", "Rails", "framework"),
    ("config/application.rb", "Rails", "framework"),
    # DB / API
    ("schema.sql", "SQL", "db_api"),
    ("db/schema.sql", "SQL", "db_api"),
    ("init.sql", "SQL", "db_api"),
    ("migrations/*", "Migrations", "db_api"),
    ("db/migrate/*", "Migrations", "db_api"),
    ("prisma/schema.prisma", "Prisma", "db_api"),
    ("drizzle.config.ts", "Drizzle", "db_api"),
    ("drizzle.config.js", "Drizzle", "db_api"),
    ("drizzle/*", "Drizzle", "db_api"),
    ("ormconfig.json", "TypeORM", "db_api"),
    ("data-source.ts", "TypeORM", "db_api"),
    (".sequelizerc", "Sequelize", "db_api"),
    ("models/*", "Sequelize", "db_api"),
    ("alembic.ini", "Alembic", "db_api"),
    ("alembic/env.py", "Alembic", "db_api"),
    ("alembic/versions/*", "Alembic", "db_api"),
    ("flyway.conf", "Flyway", "db_api"),
    ("sql/V*.sql", "Flyway", "db_api"),
    ("liquibase.properties", "Liquibase", "db_api"),
    ("changelog.xml", "Liquibase", "db_api"),
    ("db.changelog*", "Liquibase", "db_api"),
    ("sqlc.yaml", "sqlc", "db_api"),
    ("sqlc.yml", "sqlc", "db_api"),
    ("schema.graphql", "GraphQL", "db_api"),
    ("graphql.schema", "GraphQL", "db_api"),
    ("codegen.yml", "GraphQL", "db_api"),
    ("openapi.yaml", "OpenAPI", "db_api"),
    ("openapi.json", "OpenAPI", "db_api"),
    ("swagger.yaml", "OpenAPI", "db_api"),
    ("*.proto", "gRPC", "db_api"),
    ("buf.yaml", "gRPC", "db_api"),
    ("buf.gen.yaml", "gRPC", "db_api"),
    # Test / tooling maturity
    ("jest.config.js", "Jest", "tooling"),
    ("jest.config.ts", "Jest", "tooling"),
    ("vitest.config.ts", "Vitest", "tooling"),
    ("vitest.config.js", "Vitest", "tooling"),
    ("playwright.config.ts", "Playwright", "tooling"),
    ("playwright.config.js", "Playwright", "tooling"),
    ("cypress.config.ts", "Cypress", "tooling"),
    ("cypress.config.js", "Cypress", "tooling"),
    ("pytest.ini", "Pytest", "tooling"),
    ("conftest.py", "Pytest", "tooling"),
    ("tox.ini", "Tox", "tooling"),
    ("noxfile.py", "Nox", "tooling"),
    ("eslint.config.js", "ESLint", "tooling"),
    (".eslintrc.*", "ESLint", "tooling"),
    (".prettierrc", "Prettier", "tooling"),
    ("prettier.config.*", "Prettier", "tooling"),
    ("tsconfig.json", "TypeScript", "tooling"),
    ("mypy.ini", "MyPy", "tooling"),
    ("ruff.toml", "Ruff", "tooling"),
]


OWNERSHIP_FILES = {".mailmap", "AUTHORS", "CONTRIBUTORS", "CODEOWNERS", "CITATION.cff"}
